import datetime

example_race_1 = {
    "season": "2022",
    "round": "2",
    "url": "http://en.wikipedia.org/wiki/2022_Saudi_Arabian_Grand_Prix",
    "raceName": "Saudi Arabian Grand Prix",
    "Circuit": {
        "circuitId": "jeddah",
        "url": "http://en.wikipedia.org/wiki/Jeddah_Street_Circuit",
        "circuitName": "Jeddah Corniche Circuit",
        "Location": {
            "lat": "21.6319",
            "long": "39.1044",
            "locality": "Jeddah",
            "country": "Saudi Arabia",
        },
    },
    "date": "2022-03-27",
    "time": "17:00:00Z",
    "firstpracticeDate": "2022-03-25",
    "firstpracticeTime": "14:00:00Z",
    "secondpracticeDate": "2022-03-25",
    "secondpracticeTime": "17:00:00Z",
    "thirdpracticeDate": "2022-03-26",
    "thirdpracticeTime": "14:00:00Z",
    "qualifyingDate": "2022-03-26",
    "qualifyingTime": "17:00:00Z",
}

example_racedto_dict = {
    "season": 2022,
    "round": 2,
    "url": "http://en.wikipedia.org/wiki/2022_Saudi_Arabian_Grand_Prix",
    "raceName": "Saudi Arabian Grand Prix",
    "Circuit": {
        "circuitId": "jeddah",
        "url": "http://en.wikipedia.org/wiki/Jeddah_Street_Circuit",
        "circuitName": "Jeddah Corniche Circuit",
        "Location": {
            "lat": 21.6319,
            "long": 39.1044,
            "locality": "Jeddah",
            "country": "Saudi Arabia",
        },
    },
    "date": datetime.date(2022, 3, 27),
    "time": datetime.time(17, 0, tzinfo=datetime.timezone.utc),
    "firstpracticeDate": datetime.date(2022, 3, 25),
    "firstpracticeTime": datetime.time(14, 0, tzinfo=datetime.timezone.utc),
    "secondpracticeDate": datetime.date(2022, 3, 25),
    "secondpracticeTime": datetime.time(17, 0, tzinfo=datetime.timezone.utc),
    "thirdpracticeDate": datetime.date(2022, 3, 26),
    "thirdpracticeTime": datetime.time(14, 0, tzinfo=datetime.timezone.utc),
    "qualifyingDate": datetime.date(2022, 3, 26),
    "qualifyingTime": datetime.time(17, 0, tzinfo=datetime.timezone.utc),
    "sprintDate": None,
    "sprintTime": None,
}

example_racedto_tuple = (
    2022,
    2,
    "http://en.wikipedia.org/wiki/2022_Saudi_Arabian_Grand_Prix",
    "Saudi Arabian Grand Prix",
    (
        "jeddah",
        "http://en.wikipedia.org/wiki/Jeddah_Street_Circuit",
        "Jeddah Corniche Circuit",
        (21.6319, 39.1044, "Jeddah", "Saudi Arabia"),
    ),
    datetime.date(2022, 3, 27),
    datetime.time(17, 0, tzinfo=datetime.timezone.utc),
    datetime.date(2022, 3, 25),
    datetime.time(14, 0, tzinfo=datetime.timezone.utc),
    datetime.date(2022, 3, 25),
    datetime.time(17, 0, tzinfo=datetime.timezone.utc),
    datetime.date(2022, 3, 26),
    datetime.time(14, 0, tzinfo=datetime.timezone.utc),
    datetime.date(2022, 3, 26),
    datetime.time(17, 0, tzinfo=datetime.timezone.utc),
    None,
    None,
)

example_racedto_flatdict = {
    "season": 2022,
    "round": 2,
    "url": "http://en.wikipedia.org/wiki/2022_Saudi_Arabian_Grand_Prix",
    "raceName": "Saudi Arabian Grand Prix",
    "circuitCircuitid": "jeddah",
    "circuitUrl": "http://en.wikipedia.org/wiki/Jeddah_Street_Circuit",
    "circuitCircuitname": "Jeddah Corniche Circuit",
    "circuitlocationLat": 21.6319,
    "circuitlocationLong": 39.1044,
    "circuitlocationLocality": "Jeddah",
    "circuitlocationCountry": "Saudi Arabia",
    "date": datetime.date(2022, 3, 27),
    "time": datetime.time(17, 0, tzinfo=datetime.timezone.utc),
    "firstpracticeDate": datetime.date(2022, 3, 25),
    "firstpracticeTime": datetime.time(14, 0, tzinfo=datetime.timezone.utc),
    "secondpracticeDate": datetime.date(2022, 3, 25),
    "secondpracticeTime": datetime.time(17, 0, tzinfo=datetime.timezone.utc),
    "thirdpracticeDate": datetime.date(2022, 3, 26),
    "thirdpracticeTime": datetime.time(14, 0, tzinfo=datetime.timezone.utc),
    "qualifyingDate": datetime.date(2022, 3, 26),
    "qualifyingTime": datetime.time(17, 0, tzinfo=datetime.timezone.utc),
    "sprintDate": None,
    "sprintTime": None,
}

example_racedto_json = '{"season": 2022, "round": 2, "url": "http://en.wikipedia.org/wiki/2022_Saudi_Arabian_Grand_Prix", "raceName": "Saudi Arabian Grand Prix", "Circuit": {"circuitId": "jeddah", "url": "http://en.wikipedia.org/wiki/Jeddah_Street_Circuit", "circuitName": "Jeddah Corniche Circuit", "Location": {"lat": 21.6319, "long": 39.1044, "locality": "Jeddah", "country": "Saudi Arabia"}}, "date": "2022-03-27", "time": "17:00:00+00:00", "firstpracticeDate": "2022-03-25", "firstpracticeTime": "14:00:00+00:00", "secondpracticeDate": "2022-03-25", "secondpracticeTime": "17:00:00+00:00", "thirdpracticeDate": "2022-03-26", "thirdpracticeTime": "14:00:00+00:00", "qualifyingDate": "2022-03-26", "qualifyingTime": "17:00:00+00:00", "sprintDate": null, "sprintTime": null}'
